apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
  name: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.242
  externalTrafficPolicy: Local
  ports:
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: http
  - name: dns
    port: 53
    protocol: TCP
    targetPort: udp-tcp
  selector:
    app: pihole

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
  name: pihole-udp
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.242
  externalTrafficPolicy: Local
  ports:
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  selector:
    app: pihole

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pihole
  name: pihole-data
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pihole
  name: pihole-dnsmasq
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        env:
        - name: TZ
          value: America/Chicago
        - name: WEBPASSWORD
          value: admin
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
        - name: pihole-dnsmasq
          mountPath: /etc/dnsmasq.d
        ports:
        - containerPort: 80
          name: http
        - containerPort: 53
          protocol: TCP
          name: dns-tcp
        - containerPort: 53
          protocol: UDP
          name: dns-udp
      restartPolicy: Always
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: pihole-data
      - name: pihole-dnsmasq
        persistentVolumeClaim:
          claimName: pihole-dnsmasq
